### ISSUE TITLE
New Endpoints

### ISSUE THREAD

**Issue by Codeusa** [Codeusa/Netflix-Roulette-API#10]
```
Search for series containing a set of strings

Optional: Specify a year



```

http://netflixroulette.net/api/v2/usa/search/

```
Produce Episode information for a series by its Id

```
http://netflixroulette.net/api/v2/usa/tv/?netflixId=0000

```
Produce Movie Information by its Id

```

http://netflixroulette.net/api/v2/usa/movies/?netflixId=0000

```

Return fall films on netflix by a director

```

http://netflixroulette.net/api/v2/usa/director/?director=Affleck

```

Return all films with an actor on netflix 

```

http://netflixroulette.net/api/v2/usa/actor/?actor=Cage

```

convert an imdb to Netflix ID

```

http://netflixroulette.net/api/v2/usa/imdb/?id=tt11111

If you have any suggestions speak up, I will be working on these and getting them out the door soon.

Of course where it says "usa" you will use your countries ID which will be provided in the new documentation.

**Comment by mczub** [comment]
Would it be possible to return all films/series in a certain genre/category?

**Comment by Codeusa** [comment]
Can you be more specific @mczub

**Comment by mczub** [comment]
Possibly something along the lines of: /api/v2/usa/tv/?category=anime would return all anime tv shows,  /api/v2/usa/movies/?category=dramas would return all drama films. This could also go by netflix genre id number (for example, Classic Movies are id 31574, based on this list: http://www.bestmoviesonnetflix.com/netflix-hacks/complete-list-of-netflix-genres/)
